project:
  type: book

number-sections: false

book:
  title: "Digital Archaeology Labs"
  date: "9/22/2026"
  page-navigation: true
  downloads: [pdf]
  
  chapters:
    - index.qmd
    - part: "Getting Started"
      chapters: [QGIS.qmd]
    - part: "Lab 1 Historical Satellite Imagery and GIS Basics"
      chapters: [CORONA.qmd, Rasters.qmd, Vectors.qmd, Lab1.qmd]
    - part: "Lab 2 Drone Data"
    
  
  appendices: 
    - references.qmd
    
  page-footer: "Copyright 2026, Casey H. Shi || Do not share course materials"

bibliography: references.bib

format:
  html:
    theme: { light: cosmo, dark: darkly }
    code-copy: true
    
  pdf:
    documentclass: scrreprt
    toc: true
    

editor: visual

